# Generated by Django 4.1.3 on 2023-01-07 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extintor',
            fields=[
                ('tagid', models.CharField(default='1', max_length=6, primary_key=True, serialize=False)),
                ('fecha_ultima_mantencion', models.DateField(default=datetime.date.today)),
                ('edificio', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2')], default='A1', max_length=3)),
                ('fecha_sig_mantencion', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
