# Generated by Django 4.1.3 on 2022-12-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(max_length=50)),
                ('fecha_ultima_mantencion', models.DateField()),
                ('SO', models.CharField(max_length=50)),
            ],
        ),
    ]
